//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.15 at 09:20:41 AM CEST 
//


package fr.treeptik.initjava.jeurole.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nbVie" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="armePre" type="{http://www.w3schools.com}arme"/>
 *         &lt;element name="armeCourante" type="{http://www.w3schools.com}arme"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "nbVie",
    "nom",
    "armePre",
    "armeCourante"
})
@XmlRootElement(name = "personnage")
public class Personnage {

    @XmlElement(required = true)
    protected String type;
    protected int nbVie;
    @XmlElement(required = true)
    protected String nom;
    @XmlElement(required = true)
    protected Arme armePre;
    @XmlElement(required = true)
    protected Arme armeCourante;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the nbVie property.
     * 
     */
    public int getNbVie() {
        return nbVie;
    }

    /**
     * Sets the value of the nbVie property.
     * 
     */
    public void setNbVie(int value) {
        this.nbVie = value;
    }

    /**
     * Gets the value of the nom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNom() {
        return nom;
    }

    /**
     * Sets the value of the nom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNom(String value) {
        this.nom = value;
    }

    /**
     * Gets the value of the armePre property.
     * 
     * @return
     *     possible object is
     *     {@link Arme }
     *     
     */
    public Arme getArmePre() {
        return armePre;
    }

    /**
     * Sets the value of the armePre property.
     * 
     * @param value
     *     allowed object is
     *     {@link Arme }
     *     
     */
    public void setArmePre(Arme value) {
        this.armePre = value;
    }

    /**
     * Gets the value of the armeCourante property.
     * 
     * @return
     *     possible object is
     *     {@link Arme }
     *     
     */
    public Arme getArmeCourante() {
        return armeCourante;
    }

    /**
     * Sets the value of the armeCourante property.
     * 
     * @param value
     *     allowed object is
     *     {@link Arme }
     *     
     */
    public void setArmeCourante(Arme value) {
        this.armeCourante = value;
    }

}
